### PR TITLE
actualize  links to docs and examples

### PR DESCRIPTION
**Pull request by jt3k**

### CODE REVIEW

**Comment by jt3k** [comment]
what wrong ?

**Comment by krischamp** [comment]
Hi
I tried your links but still the 404 pages ....

**Comment by jt3k** [comment]
They removed the documentation for version 2, and I hope it will now be in https://reacttraining.com/react-router/

**Comment by kenbing** [comment]
There was sth wrong with the video of the home page(https://reacttraining.com/react-router/)

**Pull request closed without merging**
