### PR TITLE
There is a little mistake about word. "--history-fallback-api" 

### PR DESCRIPTION
**Pull request by SungwonKim**
--history-api-fallback is the right order.

### CODE REVIEW

**Comment by dank00** [comment]
Hi @SungwonKim I made a PR with the same change, could you add `--history-api-fallback` to the PR title so that the next person that fixes this can see its already pending :)

**Comment by SungwonKim** [comment]
Hi @dank00, I got it. Thank you for your proposal that is good idea.

**Comment by ryanflorence** [comment]
We changed the repo structure to make way more sense, previously the git history was part of the "structure" and that was a terrible idea, making PRs impossible to merge.

Now each lesson has its own directory so we can just click the merge button!

Mind updating your PR to work with the current code on the **master** branch? Thanks!

**Comment by SungwonKim** [comment]
The issue is resolved

**Pull request closed without merging**
