### PR TITLE
Doesn't tell to install npm dependencies.

### PR DESCRIPTION
**Pull request by zakdoek**
Won't run without them....

### CODE REVIEW

**Comment by FGM** [comment]
+1 : I had the same issue earlier today and fixed it the same way.

**Comment by adam-beck** [comment]
Jusy FYI, there are about 10 pull requests for this issue.

**Comment by ryanflorence** [comment]
We changed the repo structure to make way more sense, previously the git history was part of the "structure" and that was a terrible idea, making PRs impossible to merge.

Now each lesson has its own directory so we can just click the merge button!

Mind updating your PR to work with the current code on the **master** branch? Thanks!

**Comment by zedd45** [comment]
[This has been addressed](https://github.com/reactjs/react-router-tutorial/commit/4e5eb348642788551932febd3b1d6b33f08b691a#diff-e5fcb8f41de696a5e546e862cdb68003L15).

**Pull request closed without merging**
