### PR TITLE
Add missing npm install to tutorial setup

### PR DESCRIPTION
**Pull request by zedd45**
* add step to install npm dependencies

### CODE REVIEW

**Comment by zedd45** [comment]
Looks like #77 is the same thing :) 

Minus the fact that I used the short-hand syntax of the command.

**Comment by zedd45** [comment]
I think #69 and #75 also address this.

**Comment by ryanflorence** [comment]
We changed the repo structure to make way more sense, previously the git history was part of the "structure" and that was a terrible idea, making PRs impossible to merge.

Now each lesson has its own directory so we can just click the merge button!

Mind updating your PR to work with the current code on the **master** branch? Thanks!

**Comment by zedd45** [comment]
The `npm install` [already appears in the `readme`](https://github.com/reactjs/react-router-tutorial/commit/4e5eb348642788551932febd3b1d6b33f08b691a#diff-e5fcb8f41de696a5e546e862cdb68003L15), now:

**Pull request closed without merging**
