### PR TITLE
Import 'IndexLink' component before using it

### PR DESCRIPTION
**Pull request by basschoen**
import IndexLink before using it

### CODE REVIEW

**Comment by npverni** [comment]
:+1:

**Comment by pascalpp** [comment]
This was the first confusing part of an otherwise amazing tutorial. Please merge this PR : )

**Comment by ryanflorence** [comment]
I changed the repo structure to make way more sense, previously the git history was part of the "structure" and that was a terrible idea, making PRs impossible to merge.

Now each lesson has its own directory so we can just click the merge button!

Mind updating your PR to work with the current code? Thanks!

**Comment by timdorr** [comment]
Thanks!

**Pull request merged**
